Berteman/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

app_name = 'berteman'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('accounts/', include('accounts.urls')),
    path('friends/', include('friends.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('create-profile/', views.create_view, name='create'),
    re_path(r'^profile-(?P<url_profile>[\w-]+)/$',
            views.profile_view, name='profiles'),
    re_path(r'^(?P<url_profile>[\w-]+)/$', views.profile_view, name='profile')

]

friends/urls.py
from django.urls import path, include
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friend_list),
    path('list/', views.friend_list, name='add_friend'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):

    name = models.CharField(max_length=50)
    birthdate = models.DateField()
    id_line = models.CharField(max_length=10)
    desc = models.TextField()
    photo = models.ImageField(default="default.jpg", blank=True)
    username = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.CASCADE)
    url_profile = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        url = self.url_profile
        return "/accounts/{}/".format(url)

comments/models.py
from django.db import models

# Create your models here.

friends/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from . import models
from django import forms


class CreateProfile(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['name', 'birthdate', 'id_line',
                  'desc', 'photo']

Berteman/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from . import forms
from .models import UserProfile

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("accounts:create")
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            # log in the user
            user = form.get_user()
            profile = UserProfile.objects.get(username=user)
            url_final = profile.get_absolute_url()
            login(request, user)
            return redirect(url_final)
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')
    logout(request)
    return redirect('home')


def profile_view(request, url_profile):
    if request.method == "GET":
        if 'profile-' not in url_profile:
            url_profile = 'profile-' + url_profile
        prof = UserProfile.objects.get(url_profile=url_profile)
        return render(request, 'accounts/profile_show.html', {'profile': prof})


def create_view(request):
    if request.method == 'POST':
        form = forms.CreateProfile(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.username = request.user
            user = request.user
            instance.url_profile = 'profile-' + str(user)
            instance.save()
            prf = UserProfile.objects.get(username=request.user)
            url_final = prf.get_absolute_url()
            return redirect(url_final)
    else:
        form = forms.CreateProfile()
    return render(request, 'accounts/profile_setup.html', {'form': form})

comments/views.py
from django.shortcuts import render

# Create your views here.

friends/views.py
from django.shortcuts import render
from accounts.models import UserProfile

# Create your views here.


def friend_list(request):
    friends = UserProfile.objects.all()
    friend = friends.get(username=request.user)
    url = friend.url_profile
    return render(request, 'friends/add_friend.html', {'friends': friends, 'url': url})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="user">
    <h1>Login</h1>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/profile_setup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="user">
    <h1>Setup Profile</h1>
    <form action="{% url 'accounts:create' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile_show.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="user" id="profile">
    <img src="{{ profile.photo.url }}">
    <h2>{{ profile.name }}</h2>
    <p>{{ profile.birthdate }}</p>
    <p>{{ profile.id_line }}</p>
    <p>{{ profile.desc }}</p>

</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="user">
    <h1>Sign Up</h1>
    <form action="{% url 'accounts:signup' %}" class="site-form" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
</div>

{% endblock %}

friends/templates/friends/add_friend.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="user" id="friend">
    <h1>Available Users</h1>
    {% for friend in friends %}
    {% if friend.username == request.user %}
    <div id="hidden"></div>
    {% else %}
    <p><img src="{{ friend.photo.url }}"></p>
    <p id="name">{{ friend.name }}</p>
    <p id="line">{{ friend.id_line }}</p>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>BERTEMAN</title>
</head>

<body>
    <header>
        <nav id="main-navigation">
            <h1 id="logo"><img src="{% static 'logo.png' %}"></h1>
            <ul>
                {% if user.is_authenticated %}
                {% with user.get_username as usr %}
                <li><a href="{% url 'accounts:profiles' url_profile=usr %}">Home</a></li>
                {% endwith %}
                <li><a href="{% url 'friends:add_friend' %}">Add Friend</a></li>
                <li>
                    <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}

<div>
    <h2 id="homepage">Ayo mulai pertemananmu!</h2>
</div>

{% endblock %}